# Generated by Django 5.2.13 on 2026-07-01 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('obs', models.TextField(blank=True, max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='empresas.empresamodel')),
            ],
        ),
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('aberta', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='empresas.empresamodel')),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('cargo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField(db_comment='Data de nasicmento do funcionário')),
                ('telefone', models.CharField(max_length=15)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contrato_ativo', models.BooleanField(default=True)),
                ('data_admissao', models.DateField(db_comment='Data de admissão do funcionário')),
                ('data_demissao', models.DateField(blank=True, db_comment='Data de demissão do funcionário', null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='empresas.empresamodel')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MesaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('qtd_lugares', models.IntegerField(default=4)),
                ('disponivel', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='empresas.empresamodel')),
            ],
        ),
        migrations.CreateModel(
            name='ComandaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.clientemodel')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='empresas.empresamodel')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.funcionariomodel')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.mesamodel')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregue', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.comandamodel')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='empresas.empresamodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obs', models.TextField(blank=True, max_length=255)),
                ('qtd_estoque', models.PositiveIntegerField(default=4)),
                ('disponivel', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.areamodel')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='empresas.empresamodel')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedidoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd', models.PositiveIntegerField(default=4)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemPedidos', to='empresas.empresamodel')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.pedidomodel')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.produtomodel')),
            ],
        ),
    ]
