# Generated by Django 5.2.13 on 2026-07-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariomodel',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
