# Generated by Django 6.0.6 on 2026-07-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_funcionariomodel_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtomodel',
            name='qtd_estoque',
            field=models.PositiveIntegerField(),
        ),
    ]
